name: Test & Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v5

    - name: Set up
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Tests
      run: go test -race ./...

    - name: Lint
      run: "go vet ./..."

    - name: Build
      run: go build ./...